ntc_project/cart/urls.py
from django.urls import path, include
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart,name='cart'),
    path('<int:product_id>/', views.add_to_cart, name = 'add_to_cart'),
    path('<int:cart_id>/<str:dummy>/', views.remove_cart, name= 'remove_cart'),
]

ntc_project/market/urls.py
from django.urls import path
from .import views

app_name = 'market'

urlpatterns = [
    path('', views.notes_that_match_category, name = 'market_homepage'),
    path('<slug:category_slug>', views.notes_that_match_category, name = 'notes_that_match_category'),
    path('search/', views.search, name = 'search_from_query'),
    path('<slug:cat_slug>/<slug:note_slugg>', views.show_specific_note, name = 'specific_note'),
    path('<slug:cat_slug>/<slug:note_slugg>/<int:preview>', views.show_specific_note, name = 'preview_note'),

]

ntc_project/mynotes/urls.py
from django.urls import path, include
from . import views

app_name = 'mynotes'

urlpatterns = [
    path('', views.mynotes,name="mynotes"),
    path('<int:mynotes_id>/', views.selected_note, name = 'selected_note'),
    path('make_review/<int:notes_id>/', views.make_review, name = "make_review"),
]

ntc_project/ntc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('market.urls')),
    path('cart/', include('cart.urls')),
    path('mynotes/', include('mynotes.urls')),
    path('settings/', include('settings.urls')),
    path('checkout/', include ('checkout.urls')),
    #path('account/', include('account.urls')),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ntc_project/settings/urls.py
from django.urls import path, include
from . import views

app_name = 'settings'
urlpatterns = [
    path('', views.setting_payment,name="settings_payment"),
    path('policy/', views.policy_payment,name="policy_payment"),
    path('payment/', views.payment_payment,name="payment_payment"),
]

ntc_project/ntc/templates/base.html
<!DOCTYPE html>
{%load staticfiles%}
<html>
  <head>
    <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
        <href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{%static 'css/custom.css'%}">

        <link rel="stylesheet" href="{%static 'css/ratings.css'%}">
        {%if market %}

        <link rel="stylesheet" href="{%static 'css/ratings.css'%}">
        <link rel="stylesheet" href="{%static 'css/market.css'%}">
        <link rel="stylesheet" href="{%static 'css/ratings.css'%}">
        {%endif %}

        {%if note_preview%}
        <link rel="stylesheet" href="{%static 'css/ratings.css'%}">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="{%static 'css/note_preview.css'%}">

        {%endif%}

        {%if checkout%}
          <link rel="stylesheet" href="{%static 'css/setting_payment.css'%}">
        {%endif%}

        {%if cart%}
        <link rel="stylesheet" href="{%static 'css/ratings.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}">
        {%endif%}

        {%if mynotes or selected_note%}
        <link rel="stylesheet" href="{%static 'css/ratings.css'%}">
        <link rel="stylesheet" href="{%static 'css/star_rating.css'%}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/notes.css' %}">
        {%endif%}
        {%if payment %}
        <link rel="stylesheet" href="{%static 'css/setting_payment.css'%}">
        {%endif %}
        <link rel="stylesheet" href="{%static 'css/footer.css'%}">
    <title></title>
  </head>
  <body>
    {%include 'navbar.html'%}

    {%block content%}

    {%endblock%}
    <br>
    <br>
    
    <script src="{% static 'js/jquery-3.3.1.slim.min.js'%}" ></script>
    <script src="{% static 'js/popper.min.js'%}" ></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
  </body>
</html>

ntc_project/ntc/templates/footer.html
{%load staticfiles %}
<div class="row">
  <div id="footer">
  <footer>
    <hr>
    <div align="center">
      <p>&copy; 2018 Team 11</p>
    </div>
  </footer>
  </div>

</div>

ntc_project/ntc/templates/navbar.html
{%load staticfiles %}

<nav class="navbar navbar-expand-lg navbar-light bg-light content" style="padding-bottom:0px;padding-top:2px;">

    <a class="navbar-brand" href="{% url 'market:market_homepage'%}"><img src="{% static 'images/letter-e.png'%}" style = "width:50px; height:50px;"></img><div style="display:inline;">Note Taking Central</div></a><!-- <a href='https://www.freepik.com/free-vector/vintage-vector-wing_3046714.htm'>Designed by Rawpixel.com</a>-->

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>




  <div class="collapse navbar-collapse" id="navbarSupportedContent" style="width:80%;">


      <ul class="navbar-nav pml-auto " style="margin-left:auto;">
        <li class="nav-item" style="padding-top:2px;">

             <a class="nav-link" href="#"><i class="fas fa-ellipsis-v"></i><i class="fas fa-ellipsis-v"></i><i class="fas fa-ellipsis-v"></i><i class="fas fa-ellipsis-v"></i> Categories <span class="sr-only">(current)</span></a>
             <li class="nav-item">
               <form class="form-inline my-2 my-lg-0" method="get" action="{%url 'market:search_from_query'%}">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" style = 'height:45px; width:300px;' name="user_query">
                  <button style="height:35px;min-width:50px;display:inline;"class="btn btn-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search" ></i></button>
                </form>

             </li>
        </li>


      </ul>









    <ul class="navbar-nav ml-auto" style=" ">
      <li class="nav-item" style="margin-top:10px">
        <a class="nav-link" href="{% url 'mynotes:mynotes' %}">My Notes <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item" style="margin: 10px">
        <a class="nav-link" href="{%  url 'cart:cart' %}" style="max-width:60px;"><i class="fas fa-shopping-cart"></i></a>
      </li>

      <li class="nav-item" style="">
        <div id="menu">
          <ul>
            <li class="nav-item dropdown">
              <a class="nav-link special_circle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                EC
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'settings:settings_payment'%}">Account Settings</a>
                <a class="dropdown-item" href="{% url 'settings:payment_payment' %}">Payment Information</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Contact Us</a>
              </div>
            </li>

            </li>


          </ul>
        </div>


      </li>


    </ul>


  </div>
</nav>





<!--
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="padding-top:5px;padding-bottom:5px;">
  <a class="navbar-brand" href="#">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav pagination-centered">
      <li class="nav-item" style="margin-top:10px">
        <form class="form-inline my-2 my-lg-0">
           <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" style = 'min-width:600px;'>
           <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
         </form>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto" style=" margin-top:0px !important;">
      <li class="nav-item" style="margin-top:10px">
        <a class="nav-link" href="#">My Notes <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item" style="margin: 10px">
        <a class="nav-link" href="#"><i class="fas fa-shopping-cart"></i>()</a>
      </li>
      <li class="nav-item" style= "">
        <div id="menu">
          <ul>
            <li class="nav-item dropdown">
              <a class="nav-link special_circle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                EC
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Account Settings</a>
                <a class="dropdown-item" href="#">Purchase History</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Contact Us</a>
              </div>
            </li>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</nav>
-->