ntc_project/ntc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('market.urls')),
    path('cart/', include('cart.urls')),
    path('mynotes/', include('mynotes.urls')),
    path('settings/', include('settings.urls')),
    path('checkout/', include ('checkout.urls')),
    #path('account/', include('account.urls')),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ntc_project/settings/urls.py
from django.urls import path, include
from . import views

app_name = 'settings'
urlpatterns = [
    path('', views.setting_payment,name="settings_payment"),
    path('policy/', views.policy_payment,name="policy_payment"),
    path('payment/', views.payment_payment,name="payment_payment"),
]

ntc_project/settings/models.py
from django.db import models

class CreditCards(models.Model):
    fullName = models.CharField(max_length = 60)
    email = models.CharField(max_length = 60)
    address = models.CharField(max_length = 60)
    city  = models.CharField(max_length = 60)
    zip  = models.CharField(max_length = 60)
    states  = models.CharField(max_length = 60)
    nameOnCard = models.CharField(max_length = 60)
    creditCardNum = models.CharField(max_length = 60)
    expmonth = models.CharField(max_length = 60)
    cvv = models.CharField(max_length = 60)
    expYear = models.CharField(max_length = 60)

    def credit_card_id(self):
        return self.id

# Create your models here.

ntc_project/settings/views.py
from django.shortcuts import render
from .models import CreditCards


# Create your views here.

def setting_payment(request):
    print('inside of settings_payment')
    if request.method=="POST":
        newPassword= request.POST['newPassword']
        print(newPassword)
        confirmNewPassword= request.POST['confirmNewPassword']
        print(confirmNewPassword)
        currentPassword= request.POST['currentPassword']
        print(currentPassword)
        if newPassword == confirmNewPassword and newPassword != '' and currentPassword !='':
            message = 'Password has been changed'
        else:
            message = 'Passwords do not match, try again'
        return render(request,'settings/SettingAccount.html',{'message':message})
    return render(request,'settings/SettingAccount.html')

def policy_payment(request):

    return render(request,'settings/PolicyAccount.html')

def payment_payment(request):
    credit_cards = CreditCards.objects.all()
    print(credit_cards)

    if request.method=="POST":
        #read data from page,
        #check to make sure it is not empty
        #if it is not empty save information
        #print out message Try again
        firstname = request.POST['firstname']
        print(firstname)
        email = request.POST['email']
        print(email)
        address = request.POST['address']
        print(address)
        city = request.POST['city']
        print(city)
        state = request.POST['state']
        print(state)
        zip = request.POST['zip']
        print(zip)
        cardname = request.POST['cardname']
        print(cardname)
        cardnumber = request.POST['cardnumber']
        print(cardnumber)
        expmonth = request.POST['expmonth']
        print(expmonth)
        expyear = request.POST['expyear']
        print(expyear)
        cvv = request.POST['cvv']
        print(cvv)


        #check to make sure it is not empty
        if firstname != '' and email !=''and address !=''and city !=''and state !=''and zip !=''and cardname !=''and cardnumber !=''and expmonth !=''and expyear!='' and cvv!='' :
            #if it is not empty save information
            credit_card = CreditCards.objects.create(fullName=firstname,nameOnCard=cardname,email=email,address=address,city=city,zip=zip,states=state,creditCardNum=cardnumber,expmonth=expmonth,cvv=cvv,expYear=expyear)
            credit_card.save()
            print(credit_card)
            print(type(credit_card))

            message = 'Credit card has been saved'
            print('\n\nworked bro')
        else:
            #print out message Try again
            message = 'All information must be filled out, try again'
            print('\n\n inside try again')

        return render(request,'settings/PaymentAccount.html',{'payment':'payment','cards':credit_cards, 'message':message})
    return render(request,'settings/PaymentAccount.html',{'payment':'payment','cards':credit_cards})

ntc_project/settings/templates/settings/PaymentAccount.html
{%extends "base.html"%}

{%block content%}

<!-- css file-->
<div class="row" style="">
      <div class ="col-2">
        <ul class="align-middle" style="padding-top:60%;height:120vh;">
                <br><br>      <br><br>      <li>
                  <a class="" href ="{% url 'settings:settings_payment'%}"  >Account </a>
                  </li>
                  <li>
                  <a class="" href ="{% url 'settings:payment_payment'%}"  >Payment </a>
                  </li>
                  <li>
                  <a class="" href ="{% url 'settings:policy_payment'%}"  >Policy </a>
                  </li>
        </ul>

      </div>
      <div class ="col-8">
        <h1 class= "page_title" style="text-align:center;width:100%">Payment</h1>

        <form >
            <div class="mx-auto">

            <p class="text-center">
              <strong>Default Payment Method</strong>
            </p>
            <div class="card">

        <p class="text-center"><div class="card-body">
          <!-- class="card-title">Privacy Policy</h5> -->
      <p>
<strong><h2 class = "" style = "font-size: 120%">Your Credit Card</h2>
Name:</strong>
 John Smith<br><br>
      <strong>Address:</strong> <br>
      3218 Seymour St<br>
Halbur, IA 51444-7730<br><br>
      <strong>Credit Card: </strong>Visa ending in 3765</p>
    </div>
<br>

      </div>
      <br>
      <p class="text-center" style = "font-size: 150%">
      <strong>Your Credit Cards</strong>
      </p>

      <div class="card" style="width: 100%;">
  <ul class="list-group list-group-flush">







      {%for creditCard in cards%}

      <!-- Testing Payment Form-->
      <div class="row">
        <div class="col-75">
          <div class="container">
            <form>

              <div class="row">
                <div class="col-50">

                  </div>
                </div>

                <div class="col-50">
                  <h3 class="text-center">Credit Card</h3>
                  <br>
                  <label for="cname">Name on Card : </label>
                  <p>{{creditCard.nameOnCard}}</p>
                  <label for="ccnum">Credit card number :</label>
                  <p>{{creditCard.creditCardNum}}</p>
                  <label for="expmonth">Exp Month :</label>
                  <p>{{creditCard.expmonth}}</p>
                  <div class="row">
                    <div class="col-50">
                      <label for="expyear">Exp Year :</label>
                      <p>{{creditCard.expYear}}</p>
                    </div>
                    <div class="col-50">
                      <label for="cvv">CVV :</label>
                      <p>{{creditCard.cvv}}</p>
                    </div>
                  </div>
                </div>

              </div>
              <label>
              </label>
            </form>
          </div>
        </div>


      <!-- Testing Payment-->





      {%endfor%}


    </div>




  </ul>
</div>
    <!--  <div class="form-group">
 <label for="sel1">Select list:</label>
 <select class="form-control" id="sel1">
   <option>Method: Visa ending in.....</option>
   <option>Method: Visa ending in.....</option>
   <option>3</option>
   <option>4</option>-
 </select>
</div>-->
<br><br>
      <div>
        <p class="text-center">
      <!--  <button type="button" class="btn btn-primary">Save Changes</button><br><br> -->
  <br><br>
  <h4 style="margin-left:auto;margin-right:auto;" class="text-center">    <strong >Add New Payment Method Below:</strong><br></h4>

      </p>
      </div>
    </p>




<!-- Testing Payment Form-->
<div class="row">
  <div class="col-75">
    <div class="container">
      <form action="{%url 'settings:payment_payment'%}" method= "POST" >
          {%csrf_token%}

        <div class="row">
          <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
            <input type="text" id="fname" name="firstname" placeholder="John M. Doe">
            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input type="text" id="email" name="email" placeholder="john@example.com">
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="542 W. 15th Street">
            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input type="text" id="city" name="city" placeholder="New York">

            <div class="row">
              <div class="col-50">
                <label for="state">State</label>
                <input type="text" id="state" name="state" placeholder="NY">
              </div>
              <div class="col-50">
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" placeholder="10001">
              </div>
            </div>
          </div>

          <div class="col-50">
            <h3>Payment</h3>
            <label for="fname">Accepted Cards</label>
            <div class="icon-container">
              <i class="fa fa-cc-visa" style="color:navy;"></i>
              <i class="fa fa-cc-amex" style="color:blue;"></i>
              <i class="fa fa-cc-mastercard" style="color:red;"></i>
              <i class="fa fa-cc-discover" style="color:orange;"></i>
            </div>
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="John More Doe">
            <label for="ccnum">Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
            <label for="expmonth">Exp Month</label>
            <input type="text" id="expmonth" name="expmonth" placeholder="September">
            <div class="row">
              <div class="col-50">
                <label for="expyear">Exp Year</label>
                <input type="text" id="expyear" name="expyear" placeholder="2018">
              </div>
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="352">
              </div>
            </div>
          </div>

        </div>
        <label>
          <input type="checkbox" checked="checked" name="sameadr"> Shipping address same as billing
        </label>
        <input type="submit" value="Save Credit Card" class="btn30">
      </form>

      {%if message%}
      <h2>
        {{message}}
      </h2>
      {%endif%}
    </div>
  </div>
</div>

<!-- Testing Payment-->






      </div>
      <div class ="col-1">
      </div>
    </div>
  </div>

{%endblock%}

ntc_project/settings/templates/settings/PolicyAccount.html
{%extends "base.html"%}

{%block content%}

    <div class="row">
      <div class ="col-2">
        <ul class="align-middle" style="padding-top:60%;height:120vh;">
                        </br></br>      </br></br>      <li>
          <a class="" href ="{%url 'settings:settings_payment'%}"  >Account </a>
          </li>
          <li>
          <a class="" href ="{% url 'settings:payment_payment'%}"  >Payment </a>
          </li>
          <li>
          <a class="" href ="{% url 'settings:policy_payment'%}"  >Policy </a>
          </li>
        </ul>
      </div>
      <div class ="col-8">
        <h1 class= "page_title" style="text-align:center;width:100%">Policy</h1><br>
        <form >
          <div class="mx-auto">

          <p class="text-center">
        <p>
        </p>
        <div class="card">
  <p class="text-center"><div class="card-body">
    <!-- class="card-title">Privacy Policy</h5> -->
<p style="text-align: justify;-moz-text-align-last: justify; text-align-last: justify;">This privacy notice discloses the privacy practices for (website address). This privacy notice applies solely to information collected by this website. It will notify you of the following:

What personally identifiable information is collected from you through the website, how it is used and with whom it may be shared.
What choices are available to you regarding the use of your data.
The security procedures in place to protect the misuse of your information.
How you can correct any inaccuracies in the information.
Information Collection, Use, and Sharing
We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.

We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request, e.g. to ship an order.

Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.

Your Access to and Control Over Information
You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address or phone number given on our website:

See what data we have about you, if any.
Change/correct any data we have about you.
Have us delete any data we have about you.
Express any concern you have about our use of your data.
Security
We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.

Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a lock icon in the address bar and looking for "https" at the beginning of the address of the Web page.

While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.

If you feel that we are not abiding by this privacy policy, you should contact us immediately via email.</p>
Not real for eductaion purposes only.  </div>
</div></p>
      </div>
      </form>

      </div>
      <div class ="col-1">
      </div>
</div>

{%endblock%}

ntc_project/settings/templates/settings/SettingAccount.html
{%extends 'base.html'%}

{%block content%}

    <div class="row">
      <div class ="col-2">
        <ul class="align-middle" style="padding-top:60%;height:120vh;">
                </br></br>      </br></br>      <li>
                  <a class="" href ="{% url 'settings:settings_payment'%}"  >Account </a>
                  </li>
                  <li>
                  <a class="" href ="{% url 'settings:payment_payment'%}"  >Payment </a>
                  </li>
                  <li>
                  <a class="" href ="{% url 'settings:policy_payment'%}"  >Policy </a>
                  </li>
        </ul>
      </div>
      <div class ="col-8">
        <h1 class= "page_title" style="text-align:center;width:100%">Setting</h1><br>
        <form method= "POST" {%url 'settings:settings_payment'%}>
          {%csrf_token%}
          <div class="mx-auto">

        <p class="text-center" style = "font-size: 1.4em;">
  New Password
        </p>
        <p class="text-center" style ="text-align:center;width:100%;"><input type="text" style ="width:30%;"id="newPassword" name = "newPassword";><p>
        <p class="text-center" style = "font-size: 1.4em;">
        Confirm New Password
        </p>
        <p class="text-center"><input type="text" id="confirmNewPassword"type="text" style ="width:30%" name= "confirmNewPassword";> <p class="text-center">
        <p class="text-center" style = "font-size: 1.4em;">
        Current Password
        </p>
        <p class="text-center"><input type="text" style ="width:30%"id="currentPassword" name ="currentPassword";><br><br>
                </p>
        <p class="text-center">
        <button class="btn btn-primary"style = "width:15%;" type="submit" >Save</button>
        </p>
      </div>
      </form>

      {%if message%}
      <h2>
        {{message}}
      </h2>
      {%endif%}
      </div>
      <div class ="col-1">
      </div>
    </div>

    {%endblock%}