ntc_project/cart/urls.py
from django.urls import path, include
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart,name='cart'),
    path('<int:product_id>/', views.add_to_cart, name = 'add_to_cart'),
    path('<int:cart_id>/<str:dummy>/', views.remove_cart, name= 'remove_cart'),
]

ntc_project/checkout/urls.py
from django.urls import path, include
from . import views

app_name = 'checkout'

urlpatterns = [
    path('', views.checkout,name="checkout"),
    path('make_payment/', views.make_payment, name = 'make_payment'),



]

ntc_project/ntc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('market.urls')),
    path('cart/', include('cart.urls')),
    path('mynotes/', include('mynotes.urls')),
    path('settings/', include('settings.urls')),
    path('checkout/', include ('checkout.urls')),
    #path('account/', include('account.urls')),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ntc_project/cart/models.py
from django.db import models
from market.models import Notes
from django.urls import reverse
# Create your models here.


class CartItems(models.Model):
    note = models.ForeignKey(Notes, on_delete=models.CASCADE, unique=True)

    def cart_item_id(self):
        return self.id
    def remove_cart_item_url(self):
        return reverse('cart:remove_cart', args=[self.cart_item_id(),"sup"])

ntc_project/checkout/models.py
from django.db import models

# Create your models here.

ntc_project/cart/views.py
from django.shortcuts import render, redirect, reverse
from .models import CartItems
from market.models import Notes

# Create your views here.
def cart(request):
    cart_items_test_list = []
    cart_notes_ids = CartItems.objects.all()
    sum_of_price = 0
    for x in cart_notes_ids:
        cart_items_test_list.append(x)
        sum_of_price += x.note.note_price
    print(sum_of_price)
    print(cart_items_test_list)


    return render(request, "cart/cart.html" , {'cart':'cart', 'cart_items':cart_items_test_list, 'sum_of_price':sum_of_price})

def add_to_cart(request,product_id):
    #add to table
    print('in where i need to be cart views add_to_cart')
    #get Notes Item Associated with Cart Item
    note = Notes.objects.get(id = product_id)
    #create CartItem object


    try:
        carti = CartItems.objects.create(note = note)
        carti.save()

    except:
        pass

    #cart_items = CartItems.objects.get
    #return redirect('product_detail', product_id=product_id)
    return redirect(to = 'cart:cart')

def remove_cart(request, cart_id, dummy):
    cart_item_removing = CartItems.objects.get(id=cart_id)
    cart_item_removing.delete()
    return redirect(to = 'cart:cart')
    #return redirect(to='detail', product_id=product.id)

ntc_project/checkout/views.py
from django.shortcuts import render, redirect, reverse
from cart.models import CartItems
from market.models import Notes
from settings.models import CreditCards
from mynotes.models import MyPurchases

# Create your views here.

def checkout(request):
    cart_items_test_list = []
    cart_notes_ids = CartItems.objects.all()
    sum_of_price = 0
    for x in cart_notes_ids:
        cart_items_test_list.append(x)
        sum_of_price += x.note.note_price
    print(sum_of_price)
    print(cart_items_test_list)

    credit_cards = CreditCards.objects.all()

    return render(request, "checkout/checkout.html" , {'checkout':'checkout', 'cards':credit_cards, 'sum_of_price':sum_of_price})



def make_payment(self):
    user_name = 'Alan Garcia'
    credit_card = CreditCards.objects.get(id=1)

    #load everything from the cart
    cart_items_add_to_purchases_id = []
    cart_items_add = []
    cart_notes_ids = CartItems.objects.all()
    sum_of_price = 0
    for x in cart_notes_ids:
        cart_items_add_to_purchases_id.append(x.note.prod_id())
        sum_of_price += x.note.note_price
    print(sum_of_price)
    #new line





    #add everything to mynotes because you own it now
    for x in cart_items_add_to_purchases_id:
        purchased_note_id = MyPurchases.objects.create(notes_id=x)
        purchased_note_id.save()


    #call method to send email message



    #prepare message with product notes price total price put into a string
    items_bought_message ='Subject: Thank you for your purchase.\nYour new notes have added to your account.\n Below your purchases'

    for x in cart_notes_ids:

        items_bought_message+= '\n'
        items_bought_message+= '--------------------------------------\n'
        items_bought_message+= 'Product Name:  ' + str(x.note.note_name) + '\n'
        items_bought_message+= 'Product Price: ' + str(x.note.note_price) + '\n'
        items_bought_message+= 'Product Rating:' + str(x.note.ratings) + '\n'
        items_bought_message+= '\n'
    items_bought_message+= 'Total                             ' +str(sum_of_price)


    import smtplib
    smtpObj = smtplib.SMTP('smtp.gmail.com', 587)
    type(smtpObj)
    smtpObj.ehlo()
    smtpObj.starttls()

    smtpObj.login(' notetakingcenter@gmail.com ', ' jump2828 ')
    smtpObj.sendmail(' notetakingcenter@gmail.com ', ' notetakingcenter@gmail.com ',
    'Subject: Thank you for your purchase.\nYour new notes have added to your account.' + items_bought_message)
    smtpObj.quit()
    '''
    from django.core.mail import send_mail

    send_mail(
        'Review Your Purchase',
        items_bought_message,
        from_email = 'notetakingcenter@gmail.com',
        recipient_list = ['notetakingcenter@gmail.com'],
        auth_user ='notetakingcenter@gmail.com',
        auth_password = 'jump2828',
        fail_silently=False,
    )

    '''

    for x in cart_notes_ids:
        cart_item_removing = CartItems.objects.get(id=x.id)
        cart_item_removing.delete()

    print(items_bought_message)
    return redirect(to = 'mynotes:mynotes')

ntc_project/cart/templates/cart/cart.html
<!DOCTYPE html>
{% extends "base.html" %}

{% load staticfiles %}




{%block content%}
<!-- New Cart Test -->
<div class="row">
  <div class="col-1">
  </div>
  <div class="col-8">
  {% for cart_item in cart_items%}
  <div class="row">

   <div class="card-deck mx-auto">




  <div class="card">
    <a href="{{cart_item.note.get_preview_url}}"><img class="card-img-top" src="{{cart_item.note.note_snippet.url}}" alt="Card image cap" style="max-height:500px; max-width: 500px; margin-top: 20px;"></a>
    <div class="card-body">
      <h5 class="card-title">{{cart_item.note.note_name}}</h5>

     <!-- <p class="card-text">{{note.note_summary}}</p>-->
     <p class="smaller_lighter">{{cart_item.note.note_uploader_user}}</p>

     <div >
        <span class="fa fa-star checked star" style=""></span>
        <span class="fa fa-star checked star"></span>
        <span class="fa fa-star checked star"></span>
        <span class="fa fa-star star"></span>
        <span class="fa fa-star star"></span>
        <span class = "rating_info rating_number">{{cart_item.note.ratings}}</span>
        <span class = "rating_info smaller_lighter">({{cart_item.note.note_times_purchased }})</span>
      </div>

      <br>

      <div class="card-footer bg-transparent border-primary width:100%;">
        <p style="float:left;">{{cart_items.note.note_category.cat_name}}</p>
      </div>
        <a href="{{cart_item.remove_cart_item_url}}">Remove</a>
        <p style=" float:right;font-size:1.1em;">${{cart_item.note.note_price}}</p>
      </div>
    </div>
  </div>
</div>
  {%endfor%}






<!-- New Cart Test End -->










<!-- Old Version of the Cart
<div class="row">
    <div class="col-1">
    </div>
    <div class="col-8">

        <br>
        <p class="text-center page_title">Notes in the Cart</p>
       <div class="card-deck">
               <div class="card mb-3" style="max-width: 500px;">
                       <img class="card-img-top" src="{% static 'images/figure_7.2.jpg' %}" alt="Card image cap" style="max-height:300px;">
                       <div class="card-body">
                           <div class="title_price">
                                <h5 class="card-title title" style="display: inline;">Card title</h5>
                                <p class="price" style="display: inline; float: right;">$20.00</p>
                           </div>
                           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                           <a href="#">Remove</a>
                       </div>
               </div>


           <div class="card mb-3" style="max-width: 500px;">
               <img class="card-img-top" src="{% static 'images/figure_7.2.jpg' %}" alt="Card image cap" style="max-height:300px;">
               <div class="card-body">
                   <div class="title_price">
                       <h5 class="card-title title" style="display: inline;">Card title</h5>
                       <p class="price" style="display: inline; float: right;">$20.00</p>
                   </div>
                   <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                   <a href="#">Remove</a>
               </div>
           </div>

   </div>

-->


<!--Temporary-->
    </div>
    <div class="col-3">
        <br>
        <br>
        <br>
        <br>
        <br>
       <p style="font-size: 30px;">Total:</p>
       <p style="font-size: 30px;">${{sum_of_price}}</p>
       <form>
         <a href="{% url 'checkout:checkout'%}"><button type="button" class="btn btn-primary btn-lg" id="checkout_button">Checkout</button></a>
       </form>
    </div>
</div>




<!-- Temporary -->
{%endblock%}

ntc_project/cart/templates/cart/checkout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="checkout-panel">
  <div class="panel-body">
    <h2 class="title" style="text-align: center;">Checkout</h2>

    <div class="payment-method">
      <label for="card" class="method card">
        <div class="card-logos">
          <img src="img/visa_logo.png"/>
          <img src="img/mastercard_logo.png"/>
        </div>

        <div class="radio-input">
          Pay (Price) with credit card
        </div>
      </label>

      <label for="card" class="method card">
        <div class="radio-input">
          <input id="paypal" type="radio" name="payment">
          Pay £340.00 with PayPal
        </div>
      </label>
    </div>

    <div>
      <button type="button" name="button">Add Card</button>
    </div>

  <div class="panel-footer">
    <button class="btn back-btn">Back</button>
    <button class="btn next-btn">Next Step</button>
  </div>
</div>
  </body>
</html>