ntc_project/checkout/urls.py
from django.urls import path, include
from . import views

app_name = 'checkout'

urlpatterns = [
    path('', views.checkout,name="checkout"),
    path('make_payment/', views.make_payment, name = 'make_payment'),



]

ntc_project/ntc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('market.urls')),
    path('cart/', include('cart.urls')),
    path('mynotes/', include('mynotes.urls')),
    path('settings/', include('settings.urls')),
    path('checkout/', include ('checkout.urls')),
    #path('account/', include('account.urls')),
]




if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ntc_project/settings/urls.py
from django.urls import path, include
from . import views

app_name = 'settings'
urlpatterns = [
    path('', views.setting_payment,name="settings_payment"),
    path('policy/', views.policy_payment,name="policy_payment"),
    path('payment/', views.payment_payment,name="payment_payment"),
]

ntc_project/checkout/models.py
from django.db import models

# Create your models here.

ntc_project/checkout/views.py
from django.shortcuts import render, redirect, reverse
from cart.models import CartItems
from market.models import Notes
from settings.models import CreditCards
from mynotes.models import MyPurchases

# Create your views here.

def checkout(request):
    cart_items_test_list = []
    cart_notes_ids = CartItems.objects.all()
    sum_of_price = 0
    for x in cart_notes_ids:
        cart_items_test_list.append(x)
        sum_of_price += x.note.note_price
    print(sum_of_price)
    print(cart_items_test_list)

    credit_cards = CreditCards.objects.all()

    return render(request, "checkout/checkout.html" , {'checkout':'checkout', 'cards':credit_cards, 'sum_of_price':sum_of_price})



def make_payment(self):
    user_name = 'Alan Garcia'
    credit_card = CreditCards.objects.get(id=1)

    #load everything from the cart
    cart_items_add_to_purchases_id = []
    cart_items_add = []
    cart_notes_ids = CartItems.objects.all()
    sum_of_price = 0
    for x in cart_notes_ids:
        cart_items_add_to_purchases_id.append(x.note.prod_id())
        sum_of_price += x.note.note_price
    print(sum_of_price)
    #new line





    #add everything to mynotes because you own it now
    for x in cart_items_add_to_purchases_id:
        purchased_note_id = MyPurchases.objects.create(notes_id=x)
        purchased_note_id.save()


    #call method to send email message



    #prepare message with product notes price total price put into a string
    items_bought_message ='Subject: Thank you for your purchase.\nYour new notes have added to your account.\n Below your purchases'

    for x in cart_notes_ids:

        items_bought_message+= '\n'
        items_bought_message+= '--------------------------------------\n'
        items_bought_message+= 'Product Name:  ' + str(x.note.note_name) + '\n'
        items_bought_message+= 'Product Price: ' + str(x.note.note_price) + '\n'
        items_bought_message+= 'Product Rating:' + str(x.note.ratings) + '\n'
        items_bought_message+= '\n'
    items_bought_message+= 'Total                             ' +str(sum_of_price)


    import smtplib
    smtpObj = smtplib.SMTP('smtp.gmail.com', 587)
    type(smtpObj)
    smtpObj.ehlo()
    smtpObj.starttls()

    smtpObj.login(' notetakingcenter@gmail.com ', ' jump2828 ')
    smtpObj.sendmail(' notetakingcenter@gmail.com ', ' notetakingcenter@gmail.com ',
    'Subject: Thank you for your purchase.\nYour new notes have added to your account.' + items_bought_message)
    smtpObj.quit()
    '''
    from django.core.mail import send_mail

    send_mail(
        'Review Your Purchase',
        items_bought_message,
        from_email = 'notetakingcenter@gmail.com',
        recipient_list = ['notetakingcenter@gmail.com'],
        auth_user ='notetakingcenter@gmail.com',
        auth_password = 'jump2828',
        fail_silently=False,
    )

    '''

    for x in cart_notes_ids:
        cart_item_removing = CartItems.objects.get(id=x.id)
        cart_item_removing.delete()

    print(items_bought_message)
    return redirect(to = 'mynotes:mynotes')

ntc_project/checkout/templates/checkout/checkout.html
{%extends 'base.html'%}


  {%block content%}


    <h2 class="title" style="text-align: center;">Checkout</h2>
    <div class="row">
      <div class="col-2">
      </div>
      <div class="col-8" style="width:100%">


        <div class="card-deck">


        {%for creditCard in cards%}
        <div class="card" style="width:100%">
          <div class="row">
            <div class="col-75">
              <div class="container">
                <form>

                  <div class="row">
                    <div class="col-50">

                      </div>
                    </div>

                    <div class="col-50">
                      <h3 class="text-center">Credit Card</h3>
                      <br>
                      <label for="cname">Name on Card : </label>
                      <p>{{creditCard.nameOnCard}}</p>
                      <label for="ccnum">Credit card number :</label>
                      <p>{{creditCard.creditCardNum}}</p>
                      <label for="expmonth">Exp Month :</label>
                      <p>{{creditCard.expmonth}}</p>
                      <div class="row">
                        <div class="col-50">
                          <label for="expyear">Exp Year :</label>
                          <p>{{creditCard.expYear}}</p>
                        </div>
                        <div class="col-50">
                          <label for="cvv">CVV :</label>
                          <p>{{creditCard.cvv}}</p>
                        </div>
                      </div>
                    </div>

                  </div>
                  <label>
                  </label>
                </form>
              </div>
            </div>

          <div class="" style='margin-left:auto; margin-right:auto;'>
            <input type="radio" name="gender" value="use"style='margin-left:auto; margin-right:auto;'>Use  <br>

          </div>
        </div>
          {%endfor%}
            </div>

          <a href="{%url 'settings:payment_payment'%}"><button class="btnAdd btn-primary" type="button" name="addCard">Add Card</button></a>

          <a href="{% url 'checkout:make_payment'%}"><button class="btnConfirm btn-success" type="button" name="confirm">Confirm Payment</button></a>


        </div>

        <!-- Testing Payment







        <div class="payment-method">
          <label for="card" class="method card">
            Info of default card here
            <div class="radio-input">
              <input id="card" type="radio" name="payment">
              Pay (Price) with credit card #1
            </div>
          </label>
          <label for="card2" class="method card">
              Info of next card here
            <div class="radio-input">
              <input id="card2" type="radio" name="payment">
              Pay (Price) with credit card #2
            </div>
          </label>
        </div>


-->



    </div>
    <div class="col-2">
    </div>
  </div>
</div>
{%endblock%}